version: 0.2

phases:
  pre_build:
    commands:
      - cd 'ami-build'
      - echo "Installing Tomcat Files"
      - curl -o tomcat.zip https://downloads.apache.org/tomcat/tomcat-9/v9.0.55/bin/apache-tomcat-9.0.55.zip && unzip tomcat.zip
      - mv apache-tomcat-9.0.55 /tmp/tomcat9 && chmod +x /tmp/tomcat9/bin/*.sh
      - echo "Installing Packer"
      - curl -o packer.zip https://releases.hashicorp.com/packer/1.4.0/packer_1.4.0_linux_amd64.zip && unzip packer.zip
      - echo "Validating Packer template"
      - ./packer validate packer.json
  build:
    commands:
      - echo "Running Packer Build"
      - ./packer build -color=false packer.json | tee build.log
  post_build:
    commands:
      - egrep "${AWS_REGION}\:\sami\-" build.log | cut -d' ' -f2 > ami_id.txt
      # Packer doesn't return non-zero status; we must do that if Packer build failed
      - test -s ami_id.txt || exit 1
      - echo "build completed on `date`"
      - aws ssm put-parameter --type 'String' --name "/${UPSTREAMSTACK}/${ENVIRONMENT}/InspectorPrecheckAMI-${PIPELINENAME}" --value $(head -n 1 ami_id.txt) --overwrite
artifacts:
  files:
    - '**/*'
